package com.example.navigation

object AiluaDestinations {
    const val HOME = "home"
    const val MESSAGES = "messages"
    const val CONVERSATIONS = "messages"
    const val CHAT = "chat/{characterId}"
    const val GROUP_CHAT = "group_chat"
    const val CONTACTS = "contacts"
    const val RELATIONS = "relations"
    const val CHECK_PHONE = "check_phone"
    const val DIARY = "diary"
    const val MOMENTS = "moments"
    const val LIVING = "living"
    const val APPS = "apps"
    const val PROFILE = "profile/{characterId}"
    const val MEMORIES = "memories"
    const val CHARACTER_CREATOR = "character_creator"
    const val WORLD_BOOK = "world_book"
    const val WORLD_MAP = "world_map"
    const val THEATER = "theater"
    const val MAILBOX = "mailbox"
    const val CALL = "call/{characterId}"
    const val INCOMING_CALL = "incoming_call"
    const val CALL_HISTORY = "call_history"
    const val GALLERY = "gallery"

    fun chatRoute(characterId: String = "mira"): String = "chat/$characterId"
    fun profileRoute(characterId: String = "mira"): String = "profile/$characterId"
    fun callRoute(characterId: String = "mira"): String = "call/$characterId"
}
